import { useState, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  PaperPlaneRight, Bell, ChartBar, Sparkle, Robot, ArrowRight,
  WaveTriangle, FileText, Path, Broadcast,
  CheckCircle, Globe, Lightning, Gauge,
  Download, Rocket, Info, CaretRight, CaretDown,
  CheckSquare, Square, Code, Play, X,
} from '@phosphor-icons/react'
import { usePersona } from '../data/persona'

const severityColors = {
  critical: 'text-red-400 bg-red-400/10',
  high: 'text-status-degraded bg-status-degraded/10',
  medium: 'text-primary bg-primary/10',
  low: 'text-foreground-muted bg-foreground-muted/10',
}

const categoryIcons = {
  alarms: Bell, logs: FileText, traces: Path, dashboards: ChartBar,
  anomaly: WaveTriangle, slos: Gauge, 'cross-account': Globe,
}

const useCaseIcons = {
  rocket: Rocket, bell: Bell, download: Download, globe: Globe, gauge: Gauge,
}

// ─── IaC Modal ────────────────────────────────────────────────────
function IaCModal({ onClose, selectedGaps, persona }) {
  const [format, setFormat] = useState('cloudformation')
  const formats = [
    { id: 'cloudformation', label: 'CloudFormation' },
    { id: 'terraform', label: 'Terraform' },
    { id: 'json', label: 'JSON' },
  ]

  const resourceCount = selectedGaps.reduce((sum, g) => sum + g.fixCount, 0)

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
      <div className="glass-card w-[640px] max-h-[80vh] flex flex-col shadow-2xl">
        <div className="flex items-center justify-between p-4 border-b border-border-muted">
          <div>
            <h2 className="text-body-m font-semibold text-foreground">Export as Code</h2>
            <p className="text-[11px] text-foreground-muted">{selectedGaps.length} gaps selected · {resourceCount} resources</p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-background-surface-2 text-foreground-muted"><X size={16} /></button>
        </div>
        <div className="flex gap-2 px-4 pt-3">
          {formats.map(f => (
            <button key={f.id} onClick={() => setFormat(f.id)} className={`px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors ${format === f.id ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}>
              {f.label}
            </button>
          ))}
        </div>
        <div className="flex-1 overflow-y-auto p-4">
          <pre className="text-[10px] text-foreground-muted bg-background/60 rounded-lg p-4 border border-border-muted/30 overflow-x-auto leading-relaxed">
            {format === 'cloudformation' && `AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch observability setup for ${persona.applications?.[0]?.name || 'application'}
  Generated by CloudWatch Omni Agent

Resources:
${selectedGaps.map(g => `  # ${g.title}
  # ${g.fixLabel}
  ${g.id.replace('g-', '')}Setup:
    Type: AWS::CloudWatch::CompositeAlarm
    Properties:
      AlarmName: omni-${g.id.replace('g-', '')}-setup
      # ... ${g.fixCount} resources configured`).join('\n\n')}`}

            {format === 'terraform' && `# CloudWatch observability setup
# Generated by CloudWatch Omni Agent

${selectedGaps.map(g => `# ${g.title} — ${g.fixLabel}
resource "aws_cloudwatch_metric_alarm" "${g.id.replace('g-', '').replace('-', '_')}" {
  # ... ${g.fixCount} resources configured
}`).join('\n\n')}`}

            {format === 'json' && JSON.stringify({
              description: `CloudWatch observability setup - ${selectedGaps.length} gaps`,
              resources: selectedGaps.map(g => ({ id: g.id, title: g.title, count: g.fixCount, label: g.fixLabel })),
              totalResources: resourceCount,
            }, null, 2)}
          </pre>
        </div>
        <div className="flex items-center justify-between p-4 border-t border-border-muted">
          <span className="text-[10px] text-foreground-disabled">Preview only — full template generated on export</span>
          <div className="flex gap-2">
            <button className="px-4 py-2 rounded-lg bg-background-surface-1 border border-border-muted text-body-s text-foreground hover:bg-background-surface-2 transition-colors">
              Copy to clipboard
            </button>
            <button className="px-4 py-2 rounded-lg bg-primary hover:bg-primary-hover text-white text-body-s font-medium transition-colors flex items-center gap-1.5">
              <Download size={14} /> Download
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Gap Card ─────────────────────────────────────────────────────
function GapCard({ gap, selected, onToggle }) {
  const Icon = categoryIcons[gap.category] || Lightning
  const [expanded, setExpanded] = useState(false)
  const colorClass = severityColors[gap.severity] || severityColors.medium

  return (
    <div className={`glass-card p-4 transition-all ${selected ? 'border-primary/40' : ''}`}>
      <div className="flex items-start gap-3">
        <button onClick={() => onToggle(gap.id)} className="mt-0.5 flex-shrink-0">
          {selected
            ? <CheckSquare size={18} weight="fill" className="text-primary" />
            : <Square size={18} className="text-foreground-disabled hover:text-foreground-muted" />
          }
        </button>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className={`text-[9px] px-1.5 py-0.5 rounded-full font-medium ${colorClass}`}>{gap.severity}</span>
            <Icon size={14} className="text-foreground-muted" />
            <span className="text-body-s font-medium text-foreground">{gap.title}</span>
          </div>
          <p className="text-[11px] text-foreground-muted">{gap.description}</p>
          <div className="flex items-center gap-3 mt-2">
            <span className="text-[10px] text-foreground-disabled">Fix: {gap.fixLabel}</span>
            {gap.services > 0 && <span className="text-[10px] text-foreground-disabled">· {gap.services} services affected</span>}
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Use Case Card ────────────────────────────────────────────────
function UseCaseCard({ useCase, onSelect }) {
  const Icon = useCaseIcons[useCase.icon] || Rocket
  return (
    <button onClick={() => onSelect(useCase)} className="glass-card p-4 text-left hover:border-primary/30 transition-all group">
      <div className="flex items-center gap-2 mb-2">
        <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary group-hover:bg-primary/20 transition-colors">
          <Icon size={16} />
        </div>
      </div>
      <p className="text-body-s font-medium text-foreground">{useCase.title}</p>
      <p className="text-[11px] text-foreground-muted mt-1">{useCase.description}</p>
      <p className="text-[10px] text-primary mt-2">{useCase.gapIds.length} gaps addressed →</p>
    </button>
  )
}

// ─── Cost Breakdown ───────────────────────────────────────────────
function CostBreakdown({ cost }) {
  const [showProjected, setShowProjected] = useState(false)
  const data = showProjected ? cost.projected : cost.current
  return (
    <div className="glass-card p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-body-s font-semibold text-foreground">CloudWatch Cost</h3>
        <div className="flex gap-1 text-[10px]">
          <button onClick={() => setShowProjected(false)} className={`px-2 py-0.5 rounded ${!showProjected ? 'bg-primary/15 text-primary' : 'text-foreground-muted hover:text-foreground'}`}>Current</button>
          <button onClick={() => setShowProjected(true)} className={`px-2 py-0.5 rounded ${showProjected ? 'bg-primary/15 text-primary' : 'text-foreground-muted hover:text-foreground'}`}>Projected</button>
        </div>
      </div>
      <p className="text-heading-m font-semibold text-foreground mb-3">${data.total.toLocaleString()}<span className="text-body-s text-foreground-muted font-normal">/mo</span></p>
      {data.breakdown.map((item, i) => (
        <div key={i} className="flex items-center justify-between py-1">
          <span className="text-[11px] text-foreground-muted">{item.category}</span>
          <div className="flex items-center gap-2">
            <span className="text-[11px] text-foreground">${item.amount.toLocaleString()}</span>
            {item.note && <span className="text-[9px] text-foreground-disabled">{item.note}</span>}
          </div>
        </div>
      ))}
      {showProjected && cost.savings && cost.savings.length > 0 && (
        <div className="mt-3 pt-3 border-t border-border-muted/30">
          <p className="text-[9px] text-foreground-disabled uppercase tracking-wider mb-1.5">Potential savings</p>
          {cost.savings.map((s, i) => (
            <div key={i} className="flex items-center justify-between py-0.5">
              <span className="text-[11px] text-foreground-muted">{s.description}</span>
              <span className="text-[11px] text-status-active">-${s.amount.toLocaleString()}/mo</span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// ─── Posture Summary ──────────────────────────────────────────────
function PostureSummary({ applications, activeApp }) {
  const apps = activeApp === 'all' ? applications : applications.filter(a => a.id === activeApp)
  const allServices = apps.flatMap(a => a.services)
  const total = allServices.length
  const withAlarms = allServices.filter(s => s.hasAlarms).length
  const withLogs = allServices.filter(s => s.hasLogs).length
  const withTraces = allServices.filter(s => s.hasTraces).length

  const bars = [
    { label: 'Alarms', have: withAlarms, total, color: 'bg-status-degraded' },
    { label: 'Logs', have: withLogs, total, color: 'bg-green-400' },
    { label: 'Traces', have: withTraces, total, color: 'bg-purple-400' },
  ]

  return (
    <div className="glass-card p-4">
      <h3 className="text-body-s font-semibold text-foreground mb-3">Observability Posture</h3>
      <div className="flex flex-col gap-3">
        {bars.map(b => (
          <div key={b.label}>
            <div className="flex items-center justify-between mb-1">
              <span className="text-[11px] text-foreground-muted">{b.label}</span>
              <span className="text-[11px] text-foreground">{b.have} / {b.total} services</span>
            </div>
            <div className="w-full h-2 rounded-full bg-border-muted/30 overflow-hidden">
              <div className={`h-full rounded-full ${b.color}`} style={{ width: `${total > 0 ? (b.have / total) * 100 : 0}%` }} />
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function ActivityItem({ item, isLast }) {
  return (
    <div className="flex gap-3 items-start">
      <div className="flex flex-col items-center">
        <div className="w-1.5 h-1.5 rounded-full bg-primary/60 mt-1.5" />
        {!isLast && <div className="w-px flex-1 bg-border-muted mt-1" />}
      </div>
      <div className={isLast ? '' : 'pb-3'}>
        <p className="text-[11px] text-foreground-muted">{item.action}</p>
        <p className="text-[10px] text-foreground-disabled mt-0.5">{item.time}</p>
      </div>
    </div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────
export default function Day0Page() {
  const [input, setInput] = useState('')
  const { persona } = usePersona()
  const { user, applications, gaps, cost, useCases, agentActivity } = persona

  const [activeApp, setActiveApp] = useState('all')
  const [selectedGaps, setSelectedGaps] = useState(new Set())
  const [showIaCModal, setShowIaCModal] = useState(false)

  const firstName = user.name.split(' ')[0]
  const allServices = applications.flatMap(a => a.services)

  const toggleGap = (id) => {
    setSelectedGaps(prev => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }

  const selectUseCase = (uc) => {
    setSelectedGaps(new Set(uc.gapIds))
  }

  const selectAll = () => {
    if (selectedGaps.size === filteredGaps.length) {
      setSelectedGaps(new Set())
    } else {
      setSelectedGaps(new Set(filteredGaps.map(g => g.id)))
    }
  }

  const selectedGapObjects = gaps.filter(g => selectedGaps.has(g.id))
  const totalFixes = selectedGapObjects.reduce((sum, g) => sum + g.fixCount, 0)

  // Filter gaps by active application
  const filteredGaps = activeApp === 'all'
    ? gaps
    : gaps.filter(g => g.appIds?.includes('all') || g.appIds?.includes(activeApp))

  return (
    <div className="px-6 py-6 max-w-[1400px] mx-auto">

      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-1">
          <Sparkle size={16} className="text-primary" weight="fill" />
          <span className="text-[11px] text-primary font-medium">Agent active</span>
        </div>
        <h1 className="text-heading-xl font-normal tracking-tighter text-foreground">
          Welcome, {firstName}
        </h1>
        <p className="text-body-m text-foreground-muted mt-1">
          I found {allServices.length} services across {applications.length} applications. Here's your observability posture.
        </p>
      </div>

      {/* Application tabs */}
      <div className="flex gap-2 mb-6">
        <button
          onClick={() => setActiveApp('all')}
          className={`px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors ${activeApp === 'all' ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}
        >
          All ({allServices.length})
        </button>
        {applications.map(app => (
          <button
            key={app.id}
            onClick={() => setActiveApp(app.id)}
            className={`px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors ${activeApp === app.id ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}
          >
            {app.name} ({app.services.length})
          </button>
        ))}
      </div>

      {/* Main grid */}
      <div className="grid grid-cols-[1fr_320px] gap-6">

        {/* Left column */}
        <div className="flex flex-col gap-5">

          {/* Agent-suggested use cases */}
          <div>
            <h2 className="text-body-s font-semibold text-foreground mb-3">Suggested by the agent</h2>
            <div className="grid grid-cols-3 gap-3">
              {useCases.slice(0, 3).map(uc => (
                <UseCaseCard key={uc.id} useCase={uc} onSelect={selectUseCase} />
              ))}
            </div>
            {useCases.length > 3 && (
              <div className="grid grid-cols-3 gap-3 mt-3">
                {useCases.slice(3).map(uc => (
                  <UseCaseCard key={uc.id} useCase={uc} onSelect={selectUseCase} />
                ))}
              </div>
            )}
          </div>

          {/* Observability gaps */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-body-s font-semibold text-foreground">Observability Gaps</h2>
              <button onClick={selectAll} className="text-[10px] text-primary hover:text-primary-hover">
                {selectedGaps.size === filteredGaps.length ? 'Deselect all' : 'Select all'}
              </button>
            </div>
            <div className="flex flex-col gap-2">
              {filteredGaps.map(gap => (
                <GapCard key={gap.id} gap={gap} selected={selectedGaps.has(gap.id)} onToggle={toggleGap} />
              ))}
            </div>
          </div>
        </div>

        {/* Right sidebar */}
        <div className="flex flex-col gap-4">

          {/* Posture summary */}
          <PostureSummary applications={applications} activeApp={activeApp} />

          {/* Cost breakdown */}
          <CostBreakdown cost={cost} />

          {/* Agent chat */}
          <div className="glass-card p-4">
            <div className="flex items-center gap-2 mb-3">
              <Robot size={16} className="text-primary" />
              <h3 className="text-body-s font-semibold text-foreground">Ask the agent</h3>
            </div>
            <div className="relative">
              <input type="text" value={input} onChange={(e) => setInput(e.target.value)} placeholder="e.g. 'Why no tracing?'" className="w-full h-9 rounded-lg bg-background-surface-1 border border-border-muted px-3 pr-9 text-[12px] text-foreground placeholder:text-foreground-disabled focus:outline-none focus:border-primary/40 transition-colors" />
              <button className="absolute right-1.5 top-1.5 w-6 h-6 rounded-md bg-primary/10 flex items-center justify-center text-primary hover:bg-primary/20 transition-colors"><PaperPlaneRight size={12} /></button>
            </div>
          </div>

          {/* Agent activity */}
          <div className="glass-card p-4">
            <div className="flex items-center gap-2 mb-3">
              <Sparkle size={14} className="text-primary" weight="fill" />
              <h3 className="text-body-s font-semibold text-foreground">Agent Activity</h3>
            </div>
            <div className="flex flex-col">
              {agentActivity.map((item, i) => <ActivityItem key={i} item={item} isLast={i === agentActivity.length - 1} />)}
            </div>
          </div>
        </div>
      </div>

      {/* Sticky action bar */}
      {selectedGaps.size > 0 && (
        <div className="fixed bottom-0 left-14 right-0 z-40 border-t border-border-muted bg-background/90 backdrop-blur-lg px-6 py-3">
          <div className="max-w-[1400px] mx-auto flex items-center justify-between">
            <div className="flex items-center gap-3">
              <CheckCircle size={16} className="text-primary" />
              <span className="text-body-s text-foreground">{selectedGaps.size} gaps selected</span>
              <span className="text-[11px] text-foreground-muted">· {totalFixes} resources to configure</span>
            </div>
            <div className="flex items-center gap-3">
              <button onClick={() => setSelectedGaps(new Set())} className="text-[11px] text-foreground-muted hover:text-foreground">Clear</button>
              <button className="px-4 py-2 rounded-lg bg-background-surface-1 border border-border-muted text-body-s text-foreground hover:bg-background-surface-2 transition-colors flex items-center gap-1.5">
                <Play size={14} /> Apply now
              </button>
              <button onClick={() => setShowIaCModal(true)} className="px-4 py-2 rounded-lg bg-primary hover:bg-primary-hover text-white text-body-s font-medium transition-colors flex items-center gap-1.5">
                <Code size={14} /> Export as code
              </button>
            </div>
          </div>
        </div>
      )}

      {/* IaC Modal */}
      {showIaCModal && (
        <IaCModal onClose={() => setShowIaCModal(false)} selectedGaps={selectedGapObjects} persona={persona} />
      )}
    </div>
  )
}
