import { useState, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  PaperPlaneRight, Bell, ChartBar, Sparkle, Robot, ArrowRight,
  WaveTriangle, FileText, Path, Broadcast, Cpu,
  CheckCircle, Globe, Lightning, Gauge,
  Download, Rocket, Info, CaretRight, CaretDown,
  CheckSquare, Square, Code, Play, X, Gear,
} from '@phosphor-icons/react'
import { usePersona } from '../data/persona'
import { AlarmConfigModal } from '../components/AlarmConfigModal'
import { getAllRecommendedItems } from '../data/recommendations'

const severityColors = {
  critical: 'text-red-400 bg-red-400/10',
  high: 'text-orange-400 bg-orange-400/10',
  medium: 'text-primary bg-primary/10',
  low: 'text-foreground-muted bg-foreground-muted/10',
}

const categoryIcons = {
  alarms: Bell, logs: FileText, traces: Path, dashboards: ChartBar,
  anomaly: WaveTriangle, slos: Gauge, 'cross-account': Globe, 'cw-agent': Cpu, 'alarm-actions': Bell,
}

const useCaseIcons = {
  rocket: Rocket, bell: Bell, download: Download, globe: Globe, gauge: Gauge,
}

// ─── IaC Modal ────────────────────────────────────────────────────
function IaCModal({ onClose, selectedGaps, persona }) {
  const [format, setFormat] = useState('cloudformation')
  const [showShare, setShowShare] = useState(false)
  const [shareMethod, setShareMethod] = useState('slack')
  const [shareDestination, setShareDestination] = useState('')
  const [shareMessage, setShareMessage] = useState(`Here's the CloudWatch observability setup I'd like to deploy. Please review and approve.`)
  const formats = [
    { id: 'cloudformation', label: 'CloudFormation' },
    { id: 'terraform', label: 'Terraform' },
    { id: 'json', label: 'JSON' },
  ]
  const shareMethods = [
    { id: 'slack', label: 'Slack', placeholder: '#ops-team or @admin', icon: '💬' },
    { id: 'email', label: 'Email', placeholder: 'admin@company.com', icon: '✉️' },
    { id: 'jira', label: 'Jira', placeholder: 'OPS-123 or project key', icon: '🎫' },
  ]

  const resourceCount = selectedGaps.reduce((sum, g) => sum + g.fixCount, 0)

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
      <div className="glass-card w-[640px] max-h-[80vh] flex flex-col shadow-2xl">
        <div className="flex items-center justify-between p-4 border-b border-border-muted">
          <div>
            <h2 className="text-body-m font-semibold text-foreground">Export as Code</h2>
            <p className="text-[11px] text-foreground-muted">{selectedGaps.length} gaps selected · {resourceCount} resources</p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-background-surface-2 text-foreground-muted"><X size={16} /></button>
        </div>
        <div className="flex gap-2 px-4 pt-3">
          {formats.map(f => (
            <button key={f.id} onClick={() => setFormat(f.id)} className={`px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors ${format === f.id ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}>
              {f.label}
            </button>
          ))}
        </div>
        <div className="flex-1 overflow-y-auto p-4">
          <pre className="text-[10px] text-foreground-muted bg-background/60 rounded-lg p-4 border border-border-muted/30 overflow-x-auto leading-relaxed">
            {format === 'cloudformation' && `AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch observability setup for ${persona.applications?.[0]?.name || 'application'}
  Generated by CloudWatch Omni Agent

Resources:
${selectedGaps.map(g => `  # ${g.title}
  # ${g.fixLabel}
  ${g.id.replace('g-', '')}Setup:
    Type: AWS::CloudWatch::CompositeAlarm
    Properties:
      AlarmName: omni-${g.id.replace('g-', '')}-setup
      # ... ${g.fixCount} resources configured`).join('\n\n')}`}

            {format === 'terraform' && `# CloudWatch observability setup
# Generated by CloudWatch Omni Agent

${selectedGaps.map(g => `# ${g.title} — ${g.fixLabel}
resource "aws_cloudwatch_metric_alarm" "${g.id.replace('g-', '').replace('-', '_')}" {
  # ... ${g.fixCount} resources configured
}`).join('\n\n')}`}

            {format === 'json' && JSON.stringify({
              description: `CloudWatch observability setup - ${selectedGaps.length} gaps`,
              resources: selectedGaps.map(g => ({ id: g.id, title: g.title, count: g.fixCount, label: g.fixLabel })),
              totalResources: resourceCount,
            }, null, 2)}
          </pre>
        </div>
        <div className="p-4 border-t border-border-muted">
          <div className="flex items-center justify-between">
            <span className="text-[10px] text-foreground-disabled">Preview only — full template generated on export</span>
            <div className="flex gap-2">
              <button className="px-4 py-2 rounded-lg bg-background-surface-1 border border-border-muted text-body-s text-foreground hover:bg-background-surface-2 transition-colors">
                Copy to clipboard
              </button>
              <button className="px-4 py-2 rounded-lg bg-background-surface-1 border border-border-muted text-body-s text-foreground hover:bg-background-surface-2 transition-colors flex items-center gap-1.5">
                <Download size={14} /> Download
              </button>
              <button onClick={() => setShowShare(!showShare)} className={`px-4 py-2 rounded-lg text-body-s font-medium transition-colors flex items-center gap-1.5 ${showShare ? 'bg-primary text-white' : 'bg-primary hover:bg-primary-hover text-white'}`}>
                Share
              </button>
            </div>
          </div>

          {showShare && (
            <div className="mt-4 pt-4 border-t border-border-muted/30">
              <p className="text-[10px] text-foreground-disabled uppercase tracking-wider mb-2">Share with</p>
              <div className="flex gap-2 mb-3">
                {shareMethods.map(m => (
                  <button key={m.id} onClick={() => setShareMethod(m.id)} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] transition-colors ${shareMethod === m.id ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}>
                    <span>{m.icon}</span> {m.label}
                  </button>
                ))}
              </div>
              <input
                type="text"
                value={shareDestination}
                onChange={(e) => setShareDestination(e.target.value)}
                placeholder={shareMethods.find(m => m.id === shareMethod)?.placeholder}
                className="w-full h-9 rounded-lg bg-background-surface-1 border border-border-muted px-3 text-[12px] text-foreground placeholder:text-foreground-disabled focus:outline-none focus:border-primary/40 transition-colors mb-2"
              />
              <textarea
                value={shareMessage}
                onChange={(e) => setShareMessage(e.target.value)}
                rows={2}
                className="w-full rounded-lg bg-background-surface-1 border border-border-muted px-3 py-2 text-[11px] text-foreground placeholder:text-foreground-disabled focus:outline-none focus:border-primary/40 transition-colors resize-none mb-3"
              />
              <button className="w-full px-4 py-2 rounded-lg bg-primary hover:bg-primary-hover text-white text-[11px] font-medium transition-colors">
                Send via {shareMethods.find(m => m.id === shareMethod)?.label}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ─── Inline Config Editor ──────────────────────────────────────────
function ConfigEditor({ config }) {
  if (!config) return null
  const [threshold, setThreshold] = useState(config.threshold ?? '')
  const [period, setPeriod] = useState(config.period || 300)
  const [evalPeriods, setEvalPeriods] = useState(config.evalPeriods || 1)
  const [missingData, setMissingData] = useState(config.missingData || 'missing')
  const periodOpts = [{ v: 60, l: '1 min' }, { v: 300, l: '5 min' }, { v: 900, l: '15 min' }, { v: 3600, l: '1 hour' }]
  const missingOpts = [{ v: 'breaching', l: 'Treat as breaching' }, { v: 'notBreaching', l: 'Not breaching' }, { v: 'missing', l: 'Treat as missing' }]
  return (
    <div className="mt-1 mb-1 ml-6 p-2.5 rounded-lg bg-background/40 border border-border-muted/20">
      <div className="grid grid-cols-2 gap-2">
        {config.threshold !== null && <div><label className="text-[8px] text-foreground-disabled uppercase tracking-wider">Threshold ({config.unit})</label><input type="number" value={threshold} onChange={(e) => setThreshold(e.target.value)} className="w-full h-7 mt-0.5 rounded bg-background-surface-1 border border-border-muted px-2 text-[10px] text-foreground focus:outline-none focus:border-primary/40" /></div>}
        <div><label className="text-[8px] text-foreground-disabled uppercase tracking-wider">Period</label><select value={period} onChange={(e) => setPeriod(+e.target.value)} className="w-full h-7 mt-0.5 rounded bg-background-surface-1 border border-border-muted px-2 text-[10px] text-foreground focus:outline-none focus:border-primary/40">{periodOpts.map(o => <option key={o.v} value={o.v}>{o.l}</option>)}</select></div>
        <div><label className="text-[8px] text-foreground-disabled uppercase tracking-wider">Eval periods</label><input type="number" value={evalPeriods} onChange={(e) => setEvalPeriods(+e.target.value)} min={1} max={10} className="w-full h-7 mt-0.5 rounded bg-background-surface-1 border border-border-muted px-2 text-[10px] text-foreground focus:outline-none focus:border-primary/40" /></div>
        <div><label className="text-[8px] text-foreground-disabled uppercase tracking-wider">Missing data</label><select value={missingData} onChange={(e) => setMissingData(e.target.value)} className="w-full h-7 mt-0.5 rounded bg-background-surface-1 border border-border-muted px-2 text-[10px] text-foreground focus:outline-none focus:border-primary/40">{missingOpts.map(o => <option key={o.v} value={o.v}>{o.l}</option>)}</select></div>
      </div>
      <p className="text-[8px] text-foreground-disabled mt-1.5">Metric: {config.metric} · Comparison: {config.comparison}</p>
    </div>
  )
}

// ─── Gap Card with Tree Select ────────────────────────────────────
function GapCard({ gap, selectedItems, onToggleGap, onToggleService, onToggleItem, scopedServices, onConfigureAlarm }) {
  const Icon = categoryIcons[gap.category] || Lightning
  const [expanded, setExpanded] = useState(false)
  const colorClass = severityColors[gap.severity] || severityColors.medium

  // Group items by service
  const serviceGroups = {}
  for (const item of (gap.items || [])) {
    if (!serviceGroups[item.service]) serviceGroups[item.service] = []
    serviceGroups[item.service].push(item)
  }
  const serviceNames = Object.keys(serviceGroups)

  const totalItems = gap.items?.length || 0
  const selectedCount = gap.items?.filter(i => selectedItems.has(i.id)).length || 0
  const isGapSelected = totalItems === 0 && selectedItems.has(gap.id)
  const allSelected = isGapSelected || (totalItems > 0 && selectedCount === totalItems)
  const someSelected = !isGapSelected && selectedCount > 0 && selectedCount < totalItems

  return (
    <div className={`glass-card p-4 transition-all ${selectedCount > 0 ? 'border-primary/40' : ''}`}>
      <div className="flex items-start gap-3">
        <button onClick={() => onToggleGap(gap)} className="mt-0.5 flex-shrink-0">
          {allSelected
            ? <CheckSquare size={18} weight="fill" className="text-primary" />
            : someSelected
              ? <CheckSquare size={18} weight="regular" className="text-primary" />
              : <Square size={18} className="text-foreground-disabled hover:text-foreground-muted" />
          }
        </button>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className={`text-[9px] px-1.5 py-0.5 rounded-full font-medium ${colorClass}`}>{gap.severity}</span>
            <Icon size={14} className="text-foreground-muted" />
            <span className="text-body-s font-medium text-foreground">{gap.title}</span>
            {selectedCount > 0 && selectedCount < totalItems && (
              <span className="text-[9px] text-primary">{selectedCount}/{totalItems}</span>
            )}
          </div>
          <p className="text-[11px] text-foreground-muted">{gap.description}</p>
          {totalItems > 0 && (
            <button onClick={() => setExpanded(!expanded)} className="flex items-center gap-1 mt-2 text-[10px] text-primary hover:text-primary-hover">
              {expanded ? <CaretDown size={10} /> : <CaretRight size={10} />}
              {expanded ? 'Hide details' : `Show ${totalItems} items across ${serviceNames.length} services`}
            </button>
          )}
          {!totalItems && (
            <div className="flex items-center gap-3 mt-2">
              <span className="text-[10px] text-foreground-disabled">Fix: {gap.fixLabel}</span>
            </div>
          )}
        </div>
      </div>

      {/* Tree select */}
      {expanded && totalItems > 0 && (
        <div className="ml-8 mt-3 flex flex-col gap-1">
          {serviceNames.map(svcName => {
            const items = serviceGroups[svcName]
            const svcSelected = items.filter(i => selectedItems.has(i.id)).length
            const svcAll = svcSelected === items.length
            const svcSome = svcSelected > 0 && !svcAll
            const svcType = scopedServices.find(s => s.name === svcName)?.type || ''

            return (
              <div key={svcName} className="rounded-lg bg-background/30 border border-border-muted/20 p-2">
                <div className="flex items-center gap-2">
                  <button onClick={() => onToggleService(items)} className="flex-shrink-0">
                    {svcAll
                      ? <CheckSquare size={14} weight="fill" className="text-primary" />
                      : svcSome
                        ? <CheckSquare size={14} weight="regular" className="text-primary" />
                        : <Square size={14} className="text-foreground-disabled hover:text-foreground-muted" />
                    }
                  </button>
                  <span className="text-[11px] font-medium text-foreground">{svcName}</span>
                  <span className="text-[9px] text-foreground-disabled">{svcType}</span>
                </div>
                <div className="ml-6 mt-1 flex flex-col gap-0.5">
                  {items.map(item => (
                    <div key={item.id}>
                      <div className="flex items-center gap-2 py-0.5">
                        <button onClick={() => onToggleItem(item.id)} className="flex-shrink-0">
                          {selectedItems.has(item.id)
                            ? <CheckSquare size={12} weight="fill" className="text-primary" />
                            : <Square size={12} className="text-foreground-disabled hover:text-foreground-muted" />
                          }
                        </button>
                        <span className="text-[10px] text-foreground-muted flex-1">{item.name}</span>
                        {item.threshold && <span className="text-[9px] text-foreground-disabled">({item.threshold})</span>}
                        {item.config && <button onClick={() => onConfigureAlarm?.(item)} className="text-[9px] text-primary hover:text-primary-hover">Edit</button>}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

// ─── Use Case Card ────────────────────────────────────────────────
function UseCaseCard({ useCase, onSelect }) {
  const Icon = useCaseIcons[useCase.icon] || Rocket
  return (
    <button onClick={() => onSelect(useCase)} className="glass-card p-4 text-left hover:border-primary/30 transition-all group">
      <div className="flex items-center gap-2 mb-2">
        <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary group-hover:bg-primary/20 transition-colors">
          <Icon size={16} />
        </div>
      </div>
      <p className="text-body-s font-medium text-foreground">{useCase.title}</p>
      <p className="text-[11px] text-foreground-muted mt-1">{useCase.description}</p>
      <p className="text-[10px] text-primary mt-2">{useCase.gapIds.length} gaps addressed →</p>
    </button>
  )
}

// ─── Cost Breakdown ───────────────────────────────────────────────
// Per-item pricing: alarms $0.10/alarm, dashboards $3/dashboard, logs $0.50/GB,
// traces $5/million, anomaly $10/detector/mo
const UNIT_COSTS = {
  alarms: 0.10,      // per alarm per month
  logs: 2.00,        // per log config (estimated avg ingestion)
  traces: 0.50,      // per trace config (estimated)
  dashboards: 3.00,  // per dashboard
  anomaly: 10.00,    // per detector
}

function CostBreakdown({ cost, computedGaps, selectedItems }) {
  // Calculate per-item projected costs
  const projectedLines = []
  let projectedDelta = 0

  for (const gap of computedGaps) {
    const unitCost = UNIT_COSTS[gap.category]
    if (!unitCost) continue

    if (gap.items && gap.items.length > 0) {
      const selectedCount = gap.items.filter(i => selectedItems.has(i.id)).length
      if (selectedCount > 0) {
        const amount = +(selectedCount * unitCost).toFixed(2)
        projectedDelta += amount
        projectedLines.push({ category: gap.category === 'alarms' ? 'Alarms' : gap.category === 'logs' ? 'Logs' : gap.category === 'traces' ? 'Traces' : gap.category, amount, note: `${selectedCount} × $${unitCost}` })
      }
    } else if (selectedItems.has(gap.id)) {
      const amount = +(gap.fixCount * unitCost).toFixed(2)
      projectedDelta += amount
      projectedLines.push({ category: gap.category === 'dashboards' ? 'Dashboards' : gap.category === 'anomaly' ? 'Anomaly detection' : gap.category, amount, note: `${gap.fixCount} × $${unitCost}` })
    }
  }

  // Also include persona-level projected costs for non-computable gaps (stale, cross-account, slos)
  for (const p of cost.projected) {
    if (selectedItems.has(p.gapId)) {
      projectedDelta += p.amount
      projectedLines.push({ category: p.category, amount: p.amount, note: p.note })
    }
  }

  const projectedTotal = cost.current.total + projectedDelta

  return (
    <div className="glass-card p-4">
      <h3 className="text-body-s font-semibold text-foreground mb-3">CloudWatch Cost</h3>

      {/* Current */}
      <div className="flex items-baseline justify-between mb-1">
        <span className="text-[10px] text-foreground-disabled uppercase tracking-wider">Current</span>
        <span className="text-body-m font-semibold text-foreground">${cost.current.total.toLocaleString()}<span className="text-[11px] text-foreground-muted font-normal">/mo</span></span>
      </div>
      {cost.current.breakdown.map((item, i) => (
        <div key={i} className="flex items-center justify-between py-0.5">
          <span className="text-[10px] text-foreground-muted">{item.category}</span>
          <span className="text-[10px] text-foreground">${item.amount.toLocaleString()}</span>
        </div>
      ))}

      {/* Projected — only if gaps selected */}
      {projectedLines.length > 0 && (
        <div className="mt-3 pt-3 border-t border-border-muted/30">
          <div className="flex items-baseline justify-between mb-1">
            <span className="text-[10px] text-foreground-disabled uppercase tracking-wider">With selected items</span>
            <span className="text-body-m font-semibold text-foreground">
              ${projectedTotal.toLocaleString()}<span className="text-[11px] text-foreground-muted font-normal">/mo</span>
              <span className={`text-[10px] ml-1 ${projectedDelta >= 0 ? 'text-status-degraded' : 'text-status-active'}`}>
                {projectedDelta >= 0 ? '+' : ''}${projectedDelta.toFixed(2)}
              </span>
            </span>
          </div>
          {projectedLines.map((item, i) => (
            <div key={i} className="flex items-center justify-between py-0.5">
              <span className="text-[10px] text-foreground-muted">{item.category}</span>
              <div className="flex items-center gap-2">
                <span className={`text-[10px] ${item.amount >= 0 ? 'text-foreground' : 'text-status-active'}`}>
                  {item.amount >= 0 ? '+' : ''}${item.amount.toFixed(2)}
                </span>
                <span className="text-[9px] text-foreground-disabled">{item.note}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Savings */}
      {cost.savings && cost.savings.length > 0 && (
        <div className="mt-3 pt-3 border-t border-border-muted/30">
          <p className="text-[9px] text-foreground-disabled uppercase tracking-wider mb-1.5">Potential savings</p>
          {cost.savings.map((s, i) => (
            <div key={i} className="flex items-center justify-between py-0.5">
              <span className="text-[10px] text-foreground-muted">{s.description}</span>
              <span className="text-[10px] text-status-active">-${s.amount.toLocaleString()}/mo</span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// ─── Posture Summary ──────────────────────────────────────────────
function PostureSummary({ applications, activeApp }) {
  const apps = activeApp === 'all' ? applications : applications.filter(a => a.id === activeApp)
  const allServices = apps.flatMap(a => a.services)
  const total = allServices.length
  const withAlarms = allServices.filter(s => s.hasAlarms).length
  const withLogs = allServices.filter(s => s.hasLogs).length
  const withTraces = allServices.filter(s => s.hasTraces).length

  const bars = [
    { label: 'Alarms', have: withAlarms, total, color: 'bg-status-degraded' },
    { label: 'Logs', have: withLogs, total, color: 'bg-green-400' },
    { label: 'Traces', have: withTraces, total, color: 'bg-purple-400' },
  ]

  return (
    <div className="glass-card p-4">
      <h3 className="text-body-s font-semibold text-foreground mb-3">Observability Posture</h3>
      <div className="flex flex-col gap-3">
        {bars.map(b => (
          <div key={b.label}>
            <div className="flex items-center justify-between mb-1">
              <span className="text-[11px] text-foreground-muted">{b.label}</span>
              <span className="text-[11px] text-foreground">{b.have} / {b.total} services</span>
            </div>
            <div className="w-full h-2 rounded-full bg-border-muted/30 overflow-hidden">
              <div className={`h-full rounded-full ${b.color}`} style={{ width: `${total > 0 ? (b.have / total) * 100 : 0}%` }} />
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function ActivityItem({ item, isLast }) {
  return (
    <div className="flex gap-3 items-start">
      <div className="flex flex-col items-center">
        <div className="w-1.5 h-1.5 rounded-full bg-primary/60 mt-1.5" />
        {!isLast && <div className="w-px flex-1 bg-border-muted mt-1" />}
      </div>
      <div className={isLast ? '' : 'pb-3'}>
        <p className="text-[11px] text-foreground-muted">{item.action}</p>
        <p className="text-[10px] text-foreground-disabled mt-0.5">{item.time}</p>
      </div>
    </div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────
export default function Day0Page() {
  const [input, setInput] = useState('')
  const navigate = useNavigate()
  const { persona } = usePersona()
  const { user, applications, gaps, cost, useCases, agentActivity } = persona

  const [activeApp, setActiveApp] = useState('all')
  const [selectedItems, setSelectedItems] = useState(new Set())
  const [showIaCModal, setShowIaCModal] = useState(false)
  const [alarmConfigItem, setAlarmConfigItem] = useState(null)

  const firstName = user.name.split(' ')[0]
  const allServices = applications.flatMap(a => a.services)

  // Compute scoped services based on active app tab
  const scopedServices = activeApp === 'all'
    ? allServices
    : (applications.find(a => a.id === activeApp)?.services || [])

  // Dynamically compute gaps with per-service items from recommendations
  const computedGaps = (() => {
    const total = scopedServices.length
    const noAlarms = scopedServices.filter(s => !s.hasAlarms)
    const noLogs = scopedServices.filter(s => !s.hasLogs)
    const noTraces = scopedServices.filter(s => !s.hasTraces)
    const result = []

    const staleGap = gaps.find(g => g.id === 'g-stale')
    if (staleGap && (activeApp === 'all' || staleGap.appIds?.includes('all') || staleGap.appIds?.includes(activeApp))) {
      result.push(staleGap)
    }

    if (noAlarms.length > 0) {
      const items = getAllRecommendedItems(noAlarms, 'alarms')
      result.push({ id: 'g-alarms', category: 'alarms', title: `${noAlarms.length} service${noAlarms.length > 1 ? 's' : ''} have no alarms`, description: `Recommended: ${items.length} alarms for ${noAlarms.length} unmonitored services.`, severity: 'critical', services: noAlarms.length, fixCount: items.length, fixLabel: `${items.length} alarms`, items })
    }
    if (noLogs.length > 0) {
      const items = getAllRecommendedItems(noLogs, 'logs')
      result.push({ id: 'g-logs', category: 'logs', title: `Logging missing on ${noLogs.length} service${noLogs.length > 1 ? 's' : ''}`, description: `${noLogs.length} of ${total} services are not sending logs to CloudWatch.`, severity: 'high', services: noLogs.length, fixCount: items.length, fixLabel: `${items.length} log configurations`, items })
    }
    if (noTraces.length > 0) {
      const items = getAllRecommendedItems(noTraces, 'traces')
      result.push({ id: 'g-traces', category: 'traces', title: `No tracing on ${noTraces.length} service${noTraces.length > 1 ? 's' : ''}`, description: `${noTraces.length} of ${total} services have no X-Ray tracing enabled.`, severity: 'high', services: noTraces.length, fixCount: items.length, fixLabel: `${items.length} trace configurations`, items })
    }

    const extraGapIds = ['g-dashboards', 'g-anomaly', 'g-slos', 'g-cross-account', 'g-cw-agent', 'g-stale', 'g-no-actions']
    for (const g of gaps) {
      if (!extraGapIds.includes(g.id)) continue
      if (activeApp === 'all' || g.appIds?.includes('all') || g.appIds?.includes(activeApp)) {
        result.push(g)
      }
    }
    const sevOrder = { critical: 0, high: 1, medium: 2, low: 3 }
    result.sort((a, b) => (sevOrder[a.severity] ?? 3) - (sevOrder[b.severity] ?? 3))
    return result
  })()

  // Item-level selection
  const toggleItem = (itemId) => {
    setSelectedItems(prev => {
      const next = new Set(prev)
      next.has(itemId) ? next.delete(itemId) : next.add(itemId)
      return next
    })
  }

  const toggleService = (items) => {
    setSelectedItems(prev => {
      const next = new Set(prev)
      const allIn = items.every(i => next.has(i.id))
      items.forEach(i => allIn ? next.delete(i.id) : next.add(i.id))
      return next
    })
  }

  const toggleGapItems = (gap) => {
    if (!gap.items || gap.items.length === 0) {
      // For gaps without items (dashboards, anomaly, etc.), toggle the gap ID itself
      setSelectedItems(prev => {
        const next = new Set(prev)
        next.has(gap.id) ? next.delete(gap.id) : next.add(gap.id)
        return next
      })
      return
    }
    setSelectedItems(prev => {
      const next = new Set(prev)
      const allIn = gap.items.every(i => next.has(i.id))
      gap.items.forEach(i => allIn ? next.delete(i.id) : next.add(i.id))
      return next
    })
  }

  const selectAll = () => {
    const allItemIds = computedGaps.flatMap(g => g.items ? g.items.map(i => i.id) : [g.id])
    if (selectedItems.size === allItemIds.length) {
      setSelectedItems(new Set())
    } else {
      setSelectedItems(new Set(allItemIds))
    }
  }

  const totalSelected = selectedItems.size
  // Map selected items back to gap IDs for cost calculation
  const selectedGapIds = new Set()
  for (const gap of computedGaps) {
    if (gap.items && gap.items.some(i => selectedItems.has(i.id))) selectedGapIds.add(gap.id)
    if (!gap.items && selectedItems.has(gap.id)) selectedGapIds.add(gap.id)
  }

  return (
    <div className="px-6 py-6 max-w-[1400px] mx-auto">

      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center gap-2 mb-1">
          <Sparkle size={16} className="text-primary" weight="fill" />
          <span className="text-[11px] text-primary font-medium">Agent active</span>
        </div>
        <button onClick={() => navigate('/day0')} className="text-[11px] text-primary hover:text-primary-hover mb-2 flex items-center gap-1">← Back to overview</button>
        <h1 className="text-heading-xl font-normal tracking-tighter text-foreground">
          Observability Gaps
        </h1>
        <p className="text-body-m text-foreground-muted mt-1">
          I found {allServices.length} services across {applications.length} applications. Here's your observability posture.
        </p>
      </div>

      {/* Application tabs */}
      <div className="flex gap-2 mb-6">
        <button
          onClick={() => setActiveApp('all')}
          className={`px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors ${activeApp === 'all' ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}
        >
          All ({allServices.length})
        </button>
        {applications.map(app => (
          <button
            key={app.id}
            onClick={() => setActiveApp(app.id)}
            className={`px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors ${activeApp === app.id ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}
          >
            {app.name} ({app.services.length})
          </button>
        ))}
      </div>

      {/* Main grid */}
      <div className="grid grid-cols-[1fr_320px] gap-6">

        {/* Left column */}
        <div className="flex flex-col gap-5">

          {/* Observability gaps */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-body-s font-semibold text-foreground">Observability Gaps</h2>
              <button onClick={selectAll} className="text-[10px] text-primary hover:text-primary-hover">
                {totalSelected > 0 ? 'Deselect all' : 'Select all'}
              </button>
            </div>
            <div className="flex flex-col gap-2">
              {computedGaps.map(gap => (
                <GapCard key={gap.id} gap={gap} selectedItems={selectedItems} onToggleGap={toggleGapItems} onToggleService={toggleService} onToggleItem={toggleItem} scopedServices={scopedServices} onConfigureAlarm={setAlarmConfigItem} />
              ))}
            </div>
          </div>
        </div>

        {/* Right sidebar — sticky */}
        <div className="flex flex-col gap-4 self-start sticky top-6">

          {/* Selection summary + actions */}
          <div className="glass-card p-4">
            <h3 className="text-body-s font-semibold text-foreground mb-3">Selection Summary</h3>
            {totalSelected > 0 ? (
              <>
                <div className="flex items-baseline justify-between mb-1">
                  <span className="text-[11px] text-foreground-muted">{totalSelected} items selected</span>
                  <span className="text-[11px] text-foreground-disabled">{selectedGapIds.size} categories</span>
                </div>
                <div className="flex flex-col gap-1 mb-3">
                  {computedGaps.filter(g => selectedGapIds.has(g.id)).map(g => {
                    const count = g.items ? g.items.filter(i => selectedItems.has(i.id)).length : 1
                    return (
                      <div key={g.id} className="flex items-center justify-between py-0.5">
                        <span className="text-[10px] text-foreground-muted truncate">{g.title}</span>
                        <span className="text-[9px] text-foreground-disabled">{count} items</span>
                      </div>
                    )
                  })}
                </div>
                <div className="flex flex-col gap-2">
                  <button className="w-full flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-lg bg-primary hover:bg-primary-hover text-white text-[11px] font-medium transition-colors">
                    <Play size={12} /> Apply now
                  </button>
                  <button onClick={() => setShowIaCModal(true)} className="w-full flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-lg bg-background-surface-1 border border-border-muted text-[11px] text-foreground hover:bg-background-surface-2 transition-colors">
                    <Code size={12} /> Export as code
                  </button>
                  <button onClick={() => setSelectedItems(new Set())} className="text-[10px] text-foreground-muted hover:text-foreground text-center py-1">Clear selection</button>
                </div>
              </>
            ) : (
              <p className="text-[10px] text-foreground-disabled">Select gaps from the list to see a summary and take action.</p>
            )}
          </div>

          {/* Cost breakdown */}
          <CostBreakdown cost={cost} computedGaps={computedGaps} selectedItems={selectedItems} />

          {/* Agent chat */}
          <div className="glass-card p-4">
            <div className="flex items-center gap-2 mb-3">
              <Robot size={16} className="text-primary" />
              <h3 className="text-body-s font-semibold text-foreground">Ask the agent</h3>
            </div>
            <div className="relative">
              <input type="text" value={input} onChange={(e) => setInput(e.target.value)} placeholder="e.g. 'Why no tracing?'" className="w-full h-9 rounded-lg bg-background-surface-1 border border-border-muted px-3 pr-9 text-[12px] text-foreground placeholder:text-foreground-disabled focus:outline-none focus:border-primary/40 transition-colors" />
              <button className="absolute right-1.5 top-1.5 w-6 h-6 rounded-md bg-primary/10 flex items-center justify-center text-primary hover:bg-primary/20 transition-colors"><PaperPlaneRight size={12} /></button>
            </div>
          </div>
        </div>
      </div>

      {/* IaC Modal */}
      {showIaCModal && (
        <IaCModal onClose={() => setShowIaCModal(false)} selectedGaps={computedGaps.filter(g => selectedGapIds.has(g.id))} persona={persona} />
      )}

      {/* Alarm Config Modal */}
      {alarmConfigItem && (
        <AlarmConfigModal item={alarmConfigItem} onClose={() => setAlarmConfigItem(null)} onSave={(cfg) => { setAlarmConfigItem(null) }} />
      )}
    </div>
  )
}
