import { useState } from 'react'
import { X, Download } from '@phosphor-icons/react'

export function IaCExportModal({ onClose, title, subtitle }) {
  const [format, setFormat] = useState('cloudformation')
  const [showShare, setShowShare] = useState(false)
  const [shareMethod, setShareMethod] = useState('slack')
  const [shareDestination, setShareDestination] = useState('')
  const [shareMessage, setShareMessage] = useState('Here\'s the CloudWatch config I\'d like to deploy. Please review and approve.')
  const formats = [{ id: 'cloudformation', label: 'CloudFormation' }, { id: 'terraform', label: 'Terraform' }, { id: 'json', label: 'JSON' }]
  const shareMethods = [{ id: 'slack', label: 'Slack', placeholder: '#ops-team or @admin', icon: '💬' }, { id: 'email', label: 'Email', placeholder: 'admin@company.com', icon: '✉️' }, { id: 'jira', label: 'Jira', placeholder: 'OPS-123', icon: '🎫' }]

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm">
      <div className="glass-card w-[640px] max-h-[80vh] flex flex-col shadow-2xl">
        <div className="flex items-center justify-between p-4 border-b border-border-muted">
          <div><h2 className="text-body-m font-semibold text-foreground">Export as Code</h2><p className="text-[11px] text-foreground-muted">{title}{subtitle ? ` · ${subtitle}` : ''}</p></div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-background-surface-2 text-foreground-muted"><X size={16} /></button>
        </div>
        <div className="flex gap-2 px-4 pt-3">
          {formats.map(f => <button key={f.id} onClick={() => setFormat(f.id)} className={`px-3 py-1.5 rounded-lg text-[11px] font-medium transition-colors ${format === f.id ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}>{f.label}</button>)}
        </div>
        <div className="flex-1 overflow-y-auto p-4">
          <pre className="text-[10px] text-foreground-muted bg-background/60 rounded-lg p-4 border border-border-muted/30 overflow-x-auto leading-relaxed">
            {format === 'cloudformation' && `AWSTemplateFormatVersion: '2010-09-09'\nDescription: ${title || 'CloudWatch resources'}\n  Generated by CloudWatch Omni Agent\n\nResources:\n  # Selected items will be included here\n  # Full template generated on export`}
            {format === 'terraform' && `# ${title || 'CloudWatch resources'}\n# Generated by CloudWatch Omni Agent\n\n# Selected items will be included here\n# Full template generated on export`}
            {format === 'json' && JSON.stringify({ description: title || 'CloudWatch resources', generatedBy: 'CloudWatch Omni Agent', resources: '...' }, null, 2)}
          </pre>
        </div>
        <div className="p-4 border-t border-border-muted">
          <div className="flex items-center justify-between">
            <span className="text-[10px] text-foreground-disabled">Preview only</span>
            <div className="flex gap-2">
              <button className="px-4 py-2 rounded-lg bg-background-surface-1 border border-border-muted text-body-s text-foreground hover:bg-background-surface-2 transition-colors">Copy</button>
              <button className="px-4 py-2 rounded-lg bg-background-surface-1 border border-border-muted text-body-s text-foreground hover:bg-background-surface-2 transition-colors flex items-center gap-1.5"><Download size={14} /> Download</button>
              <button onClick={() => setShowShare(!showShare)} className="px-4 py-2 rounded-lg bg-primary hover:bg-primary-hover text-white text-body-s font-medium transition-colors">Share</button>
            </div>
          </div>
          {showShare && (
            <div className="mt-4 pt-4 border-t border-border-muted/30">
              <div className="flex gap-2 mb-3">{shareMethods.map(m => <button key={m.id} onClick={() => setShareMethod(m.id)} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[11px] transition-colors ${shareMethod === m.id ? 'bg-primary/15 text-primary border border-primary/30' : 'bg-background-surface-1 text-foreground-muted border border-border-muted hover:border-primary/20'}`}>{m.icon} {m.label}</button>)}</div>
              <input type="text" value={shareDestination} onChange={(e) => setShareDestination(e.target.value)} placeholder={shareMethods.find(m => m.id === shareMethod)?.placeholder} className="w-full h-9 rounded-lg bg-background-surface-1 border border-border-muted px-3 text-[12px] text-foreground placeholder:text-foreground-disabled focus:outline-none focus:border-primary/40 mb-2" />
              <textarea value={shareMessage} onChange={(e) => setShareMessage(e.target.value)} rows={2} className="w-full rounded-lg bg-background-surface-1 border border-border-muted px-3 py-2 text-[11px] text-foreground focus:outline-none focus:border-primary/40 resize-none mb-3" />
              <button className="w-full px-4 py-2 rounded-lg bg-primary hover:bg-primary-hover text-white text-[11px] font-medium">Send via {shareMethods.find(m => m.id === shareMethod)?.label}</button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
